name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate coverage report
      run: npm test -- --coverage

    - name: Send coverage report to Coveralls
      uses: coverallsapp/github-action@v2.1.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
